# See http://www.appveyor.com/docs/appveyor-yml for many more options
before_build:
 nuget restore

before_test:
- ps: |
    $ErrorActionPreference = 'Stop';
    $sqlServerUrl = "$($env:downloadUrl)/SQLServer2016-x64-ENU.exe"
    $sqlServerUrlBox = "$($env:downloadUrl)/SQLServer2016-x64-ENU.box"
    # instance name express to be able to switch easy between express and eval
    $sqlServerSilentArgs = "/IACCEPTSQLSERVERLICENSETERMS /Q /ACTION=install /INSTANCENAME=MSSQLSERVER /UPDATEENABLED=FALSE /FEATURES=SQLEngine /SQLSYSADMINACCOUNTS=`"BUILTIN\Administrators`""
    $tempDir = Join-Path (Get-Item $env:TEMP).FullName "sql2016Eval"
    if ((Test-Path $tempDir) -eq $false) { New-Item -ItemType Directory -Path $tempDir}
    $fileFullPath = "$tempDir\SQLServer.exe"
    $fileFullPathBox = "$tempDir\SQLServer.box"
    Write-Host "Downloading SQL Server..." (Get-Date).DateTime
    (New-Object Net.WebClient).DownloadFile($sqlServerUrl , $fileFullPath)
    (New-Object Net.WebClient).DownloadFile($sqlServerUrlBox , $fileFullPathBox)
    Write-Host "Extracting SQL Server..." (Get-Date).DateTime
    $extractPath = "$tempDir\SQLEXPR"
    Start-Process "$fileFullPath" "/Q /x:`"$extractPath`"" -Wait
    Write-Host "Installing SQL Server..." (Get-Date).DateTime
    $setupPath = "$extractPath\setup.exe"
    Start-Process $setupPath "$sqlServerSilentArgs" -Wait
    Write-Host "SQL Server Installation completed" (Get-Date).DateTime
    # downloading and installing Power BI Report Server
    $pbiServerUrl = $env:pbirsDownloadUrl
    $pbiServerTempDir = Join-Path (Get-Item $env:TEMP).FullName "PBIServer"
    if ((Test-Path $pbiServerTempDir) -eq $false) { New-Item -ItemType Directory -Path $pbiServerTempDir }
    $pbiServerFileFullPath = "$pbiServerTempDir\PowerBIReportServer.exe"
    $pbiServerSilentArgs = "/Q /NORESTART IACCEPTLICENSETERMS=true"

    Write-Host "Importing SQLPS Module..." (Get-Date).DateTime
    Import-Module "C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\sqlps\sqlps.psd1"
    Write-Host "SQLPS Module imported" (Get-Date).DateTime


    try {
        Write-Host "Downloading Power BI Report Server from $pbiServerUrl ..." (Get-Date).DateTime
        (New-Object Net.WebClient).DownloadFile($pbiServerUrl , $pbiServerFileFullPath)

        Write-Host "Installing Power BI Report Server..." (Get-Date).DateTime
        Start-Process $pbiServerFileFullPath "$pbiServerSilentArgs" -Wait

        Write-Host "Power BI Report Server Installation completed" (Get-Date).DateTime
    } catch {
        Write-Error "Exception occurred while downloading Power BI Report Server: $_.Exception.Message"
        throw
    }
    
    # Activate verbose on Powershell
    $VerbosePreference = "continue" 

    # downloading Reporting Services Tools
    Write-Host "Downloading Reporting Services tools..." (Get-Date).DateTime
    Install-Module ReportingServicesTools -Force
    
    # configuring Power BI Report Server Database
    Write-Host "Configuring Report Server database..." (Get-Date).DateTime
    Set-RsDatabase -ReportServerInstance PBIRS -ReportServerVersion SQLServer2017 -DatabaseServerName localhost -DatabaseName ReportServer -DatabaseCredentialType ServiceAccount -Confirm:$false
    
    # configuring Power BI Report Server URLs
    Write-Host "Configuring Report Server URL for Server..." (Get-Date).DateTime
    Set-RsUrlReservation -ReportServerInstance PBIRS -ReportServerVersion SQLServer2017
    
    # initializing Power BI Report Server
    Write-Host "Initialize Power BI Report Server..." (Get-Date).DateTime
    Initialize-Rs -ReportServerInstance PBIRS -ReportServerVersion SQLServer2017
    
    # restarting Power BI Report Server
    Write-Host "Restarting Power BI Report Server Service..." (Get-Date).DateTime
    Stop-Service PowerBIReportServer
    Start-Service PowerBIReportServer
    Start-Sleep -s 10
    Write-Host "Power BI Report Server configured successfully..." (Get-Date).DateTime

on_failure:
- ps: |
    Get-ChildItem "C:\Program Files\Microsoft Power BI Report Server\PBIRS\LogFiles\*.log" | ForEach-Object { "$(write-host $_.Name -foregroundcolor magenta) `n$(Get-Content $_.FullName -Raw)"}
	Write-Host "Url Registration" -foregroundcolor magenta
	netsh http show urlacl

test_script:
 TestForCI.cmd
